[2025-01-22 03:41:24,071: INFO: main: Welcome to our custom log]
[2025-01-22 03:42:18,900: INFO: main: Welcome to our custom log]
[2025-01-22 10:03:02,986: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 10:03:02,994: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 10:03:02,997: INFO: common: created directory at: artifacts]
[2025-01-22 10:03:02,999: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-22 10:03:03,043: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 10:03:47,583: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 10:06:03,732: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 10:06:03,740: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 10:06:03,740: INFO: common: created directory at: artifacts]
[2025-01-22 10:06:03,746: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-22 10:06:03,748: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 10:06:40,181: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 10:49:40,691: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-22 10:49:40,694: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 10:49:40,696: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 10:49:40,696: INFO: common: created directory at: artifacts]
[2025-01-22 10:49:40,696: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-22 10:49:40,698: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 10:50:49,312: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 10:50:50,700: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-22 16:48:41,978: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 16:48:42,003: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 16:48:42,048: INFO: common: created directory at: artifacts]
[2025-01-22 16:48:42,052: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-22 16:49:11,841: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-22 17:35:13,739: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-22 17:35:13,751: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 17:35:13,759: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 17:35:13,759: INFO: common: created directory at: artifacts]
[2025-01-22 17:35:13,759: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-22 17:35:13,763: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 17:36:14,039: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 17:36:14,859: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-22 17:36:14,859: INFO: main: *******************]
[2025-01-22 17:36:14,859: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-22 17:36:14,859: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 17:36:14,859: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 17:36:14,859: INFO: common: created directory at: artifacts]
[2025-01-22 17:36:14,859: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-22 17:36:15,508: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-22 17:36:15,733: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-22 18:11:30,351: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 18:11:30,356: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 18:11:30,357: INFO: common: created directory at: artifacts]
[2025-01-22 18:11:30,365: INFO: common: created directory at: artifacts\training]
[2025-01-22 18:12:55,260: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 18:12:55,262: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 18:12:55,263: INFO: common: created directory at: artifacts]
[2025-01-22 18:12:55,264: INFO: common: created directory at: artifacts\training]
[2025-01-22 18:36:21,162: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-22 18:36:21,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 18:36:21,164: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 18:36:21,164: INFO: common: created directory at: artifacts]
[2025-01-22 18:36:21,164: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-22 18:36:21,164: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 18:37:17,858: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 18:37:19,992: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-22 18:37:19,994: INFO: main: *******************]
[2025-01-22 18:37:19,994: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-22 18:37:19,996: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 18:37:19,998: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 18:37:20,000: INFO: common: created directory at: artifacts]
[2025-01-22 18:37:20,002: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-22 18:37:20,894: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-22 18:37:21,286: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-22 18:37:21,286: INFO: main: *******************]
[2025-01-22 18:37:21,286: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-01-22 18:37:21,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 18:37:21,290: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 18:37:21,295: INFO: common: created directory at: artifacts]
[2025-01-22 18:37:21,295: INFO: common: created directory at: artifacts\training]
[2025-01-22 18:37:22,070: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "C:\GITHUB\Renal-Tumor-Classification\main.py", line 38, in <module>
    model_trainer.main()
  File "c:\github\renal-tumor-classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "c:\github\renal-tumor-classification\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2025-01-22 18:40:48,666: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-22 18:40:48,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 18:40:48,673: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 18:40:48,673: INFO: common: created directory at: artifacts]
[2025-01-22 18:40:48,673: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-22 18:40:48,677: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 18:41:55,287: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-22 18:41:56,163: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-22 18:41:56,163: INFO: main: *******************]
[2025-01-22 18:41:56,163: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-22 18:41:56,163: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 18:41:56,163: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 18:41:56,163: INFO: common: created directory at: artifacts]
[2025-01-22 18:41:56,163: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-22 18:41:56,623: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-22 18:41:56,871: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-22 18:41:56,871: INFO: main: *******************]
[2025-01-22 18:41:56,871: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-01-22 18:41:56,887: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 18:41:56,887: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 18:41:56,887: INFO: common: created directory at: artifacts]
[2025-01-22 18:41:56,887: INFO: common: created directory at: artifacts\training]
[2025-01-22 18:42:46,059: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-22 22:49:35,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-22 22:49:35,040: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-22 22:49:35,044: INFO: common: created directory at: artifacts]
[2025-01-22 22:50:34,715: INFO: common: json file saved at: scores.json]
[2025-01-22 22:50:41,860: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-22 22:50:43,780: INFO: builder_impl: Assets written to: C:\Users\Udith\AppData\Local\Temp\tmp6gclrhfs\model\data\model\assets]
[2025-01-23 02:43:44,110: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-23 02:43:44,110: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 02:43:44,110: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 02:43:44,110: INFO: common: created directory at: artifacts]
[2025-01-23 02:43:44,116: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-23 02:43:44,116: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-23 02:44:19,133: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1XbXIR1ed3eURyGAV5c8-ciilZMfD96hb/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-23 02:44:20,251: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-23 02:44:31,528: INFO: stage_02_prepare_base_model: *******************]
[2025-01-23 02:44:31,528: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-23 02:44:31,528: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 02:44:31,528: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 02:44:31,528: INFO: common: created directory at: artifacts]
[2025-01-23 02:44:31,528: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-23 02:44:32,110: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-23 02:44:32,332: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-23 02:44:37,821: INFO: stage_03_model_training: *******************]
[2025-01-23 02:44:37,821: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-01-23 02:44:37,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 02:44:37,821: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 02:44:37,821: INFO: common: created directory at: artifacts]
[2025-01-23 02:44:37,821: INFO: common: created directory at: artifacts\training]
[2025-01-23 02:45:27,633: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-23 02:45:34,054: INFO: stage_04_model_evaluation: *******************]
[2025-01-23 02:45:34,054: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-01-23 02:45:34,055: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-23 02:45:34,055: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-23 02:45:34,055: INFO: common: created directory at: artifacts]
[2025-01-23 02:45:50,539: INFO: common: json file saved at: scores.json]
[2025-01-23 02:45:50,539: INFO: common: json file saved at: scores.json]
[2025-01-23 02:45:50,539: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-01-23 03:07:34,819: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.8.103:8080]
[2025-01-23 03:07:34,819: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-23 03:08:07,319: INFO: _internal: 192.168.8.103 - - [23/Jan/2025 03:08:07] "GET / HTTP/1.1" 200 -]
[2025-01-23 03:08:07,437: INFO: _internal: 192.168.8.103 - - [23/Jan/2025 03:08:07] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-01-23 03:08:45,356: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:08:45] "GET / HTTP/1.1" 200 -]
[2025-01-23 03:08:45,465: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:08:45] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-01-23 03:09:11,953: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:09:11] "GET / HTTP/1.1" 200 -]
[2025-01-23 03:09:18,119: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:09:18] "GET / HTTP/1.1" 200 -]
[2025-01-23 03:14:03,918: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.8.103:8080]
[2025-01-23 03:14:03,918: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-23 03:14:11,998: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:14:11] "GET / HTTP/1.1" 200 -]
[2025-01-23 03:14:47,314: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\GITHUB\Renal-Tumor-Classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\renal-tumor-classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-01-23 03:14:47,347: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:14:47] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-23 03:22:59,432: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:22:59] "GET / HTTP/1.1" 200 -]
[2025-01-23 03:23:08,579: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\GITHUB\Renal-Tumor-Classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\renal-tumor-classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Udith\.conda\envs\ren\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-01-23 03:23:08,579: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:23:08] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-23 03:28:40,192: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.8.103:8080]
[2025-01-23 03:28:40,192: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-23 03:28:48,002: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:28:48] "GET / HTTP/1.1" 200 -]
[2025-01-23 03:28:59,507: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:28:59] "POST /predict HTTP/1.1" 200 -]
[2025-01-23 03:29:16,890: INFO: _internal: 127.0.0.1 - - [23/Jan/2025 03:29:16] "POST /predict HTTP/1.1" 200 -]
